### ISSUE TITLE
[bootstrap] Some errors (36) in CSS3 validity check

### ISSUE THREAD

**Issue by dervishe-** [dervishe-/f-droid-web#32]
When i checked the css of the bootstrap theme, the validator signal 36 errors (level CSS3)

**Comment by pserwylo** [comment]
Hey, this is from the standard boostrap file (the minified one). I will rename my file to be "theme.css" rather than "boostrap.theme.css" - because it now lives in the /template/boostrap/css directory anyway - so clearly belongs to the bootstrap theme. However, "bootstrap.min.css" will remain, and will continue to have validator errors. A large part of this is due to the fact that they use vendor prefixes on their classes (e.g. "-moz-_" or "-webkit-_") and approx 50% of these will not validate on each browser. I don't think this is a problem, as it is the way these crappy vendor prefixes were designed (that is - browsers ignore things destined for other browsers).

**Comment by dervishe-** [comment]
Ok, no trouble, i close this one :)
